### PR TITLE
Test-bot distance based autonomous

### PR DESCRIPTION
**Pull request by porglezomp**
This is a reworked version of #7, which squashes some commits to clean up the history a little bit.
Don't merge this until #5 is merged.

### CODE REVIEW

**Comment by porglezomp** [comment]
Code review: Looks good to me, @claytonrie can check it over if he wants.
Unless he says otherwise, I'll merge it once #5 lands.
:+1:

**Comment by porglezomp** [comment]
Hm, looks like I might need to do something annoying to make this work.

**Comment by a2aaron** [comment]
What wrong with it?

**Comment by porglezomp** [comment]
It's tracking all of my commits, I'm worried what mess we might get if we merge it.

**Comment by a2aaron** [comment]
Do you want me to make a new PR and see if that helps?

**Comment by porglezomp** [comment]
Try making one, and only hit the create button if it only lists your few commits. If it lists more, then we'll just go ahead and merge this one.

**Comment by a2aaron** [comment]
Nope, lists your commits.

**Comment by porglezomp** [comment]
I think I've found a description of the issue here: http://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch. Sounds like it's perfectly normal, so I'll merge it.

**Comment by porglezomp** [comment]
:tada: Congratulations on your first merged PR here! :tada:

**Comment by vivianbp** [comment]
:tada: partyyyyyyyy :tada:

**Pull request merged**
